language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake
      - gnupg2
      - valgrind
  homebrew:
    packages:
      - cmake
      - gnupg2

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..

script:
  - ./run-build.sh

after_failure:
  - echo "Test ouput:"
  - cat test/out.log