language: c

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake
      - gnupg
      - valgrind
  homebrew:
    packages:
      - cmake
      - gnupg

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr/local ..

script:
  - ./run-build.sh
