.TH git-chat-import-key 1 "@CMAKE_COMPILATION_DATE@" "git-chat @CMAKE_PROJECT_VERSION_MAJOR@.@CMAKE_PROJECT_VERSION_MINOR@.@CMAKE_PROJECT_VERSION_PATCH@" "git-chat manual"

.SH NAME
git-chat-import-key \- import GnuPG public keys into a channel


.SH SYNOPSIS
.sp
.nf
\fIgit-chat-import-key\fR [\-\-gpg\-home <path>] [\-\-] <key fpr>...
\fIgit-chat-import-key\fR (\-f | \-\-file) <path>
\fIgit-chat-import-key\fR (\-h | \-\-help)


.SH DESCRIPTION
To ensure that other users can include you as a recipient to messages sent in a particular channel, it might be necessary to import your GnuPG public key into that channel. In general, your GnuPG public keys should be imported if \fB.git-chat/keys\fR does not contain a file whose name is the fingerprint of your public key.

When a key is imported into the channel, a new commit at the tip of the channel branch is created and must be published.


.SH OPTIONS
.TP
\-\-gpg\-home <path>
Specify an alternate GNUPGHOME from which keys will be exported and imported into the git-chat keyring.

.TP
\-f, \-\-file <path>
Import public key from a key file. May be defined more than once to import multiple keys.

.TP
\-h, \-\-help
Print a simple synopsis and exit.


.SH SEE ALSO
\fBgit-chat-channel\fR(1)


.SH REPORTING BUGS
@DOCS_REPORTING_BUGS_SECTION@


.SH AUTHOR
@DOCS_AUTHORS_SECTION@
