.TH git-chat-init 1 "@CMAKE_COMPILATION_DATE@" "git-chat @CMAKE_PROJECT_VERSION_MAJOR@.@CMAKE_PROJECT_VERSION_MINOR@" "git-chat manual"

.SH NAME
git-chat-init \- initialize a git-chat messaging space

.SH SYNOPSIS
.sp
.nf
\fIgit-chat-init\fR [(-n | --name) <alias>] [(-d | --description) <desc>]
\fIgit-chat-init\fR (-h | --help)


.SH DESCRIPTION
Initialize a git-chat messaging space. A messaging space must be initialized before it can be used.

\fIgit-chat-init\fR calls \fBgit-init\fR(1) to first initialize the underlying git repository, and then creates git-chat configuration files and metadata.


.SH OPTIONS
.TP
\-n, \-\-name <alias>
Specify a alias name for the master channel.

.TP
\-d, \-\-description <desc>
Specify a description for the space. This description is used to provide more information about what the chat space is used for.

.TP
\-h, \-\-help
Print a simple synopsis and exit.


.SH FILE/DIRECTORY LAYOUT
@DOCS_FILE_DIRECTORY_LAYOUT_SECTION@


.SH SEE ALSO
\fBgit-chat\fR(1)


.SH REPORTING BUGS
@DOCS_REPORTING_BUGS_SECTION@


.SH AUTHOR
@DOCS_AUTHORS_SECTION@
