set(CPACK_GENERATOR "RPM")

set(CPACK_RPM_FILE_NAME RPM-DEFAULT)
set(CPACK_RPM_PACKAGE_RELEASE 1)
set(CPACK_RPM_PACKAGE_GROUP "System Tools")
set(CPACK_RPM_PACKAGE_URL "https://github.com/brandon1024/gitchat")

set(CPACK_RPM_PACKAGE_REQUIRES "gpgme, git")
set(CPACK_RPM_PACKAGE_RELEASE_DIST ON)
